package org.kjs.stocknews.common

enum class ResultCode(val code: String, val message: String) {
    OK("OK", "SUCCESS"),
    BAD_REQUEST("BAD_REQUEST", "잘못된 요청입니다."),
    NOT_FOUND("NOT_FOUND", "요청한 리소스를 찾을 수 없습니다."),
    INTERNAL_ERROR("INTERNAL_ERROR", "서버 오류가 발생했습니다."),

    // 요청 형식 자체가 잘못된 경우 - 클라이언트 실수를 INTERNAL_ERROR로 감추지 않기 위해 분리한다.
    MALFORMED_REQUEST_BODY("MALFORMED_REQUEST_BODY", "요청 본문을 읽을 수 없습니다. 형식을 확인해주세요."),
    METHOD_NOT_ALLOWED("METHOD_NOT_ALLOWED", "지원하지 않는 요청 방식입니다."),

    // 인프라 장애 - 프론트/운영자가 응답 코드만으로 원인 계층을 구분할 수 있도록 분리한다.
    DATABASE_UNAVAILABLE("DATABASE_UNAVAILABLE", "데이터베이스에 연결할 수 없습니다. 잠시 후 다시 시도해주세요."),
    DATABASE_TIMEOUT("DATABASE_TIMEOUT", "데이터 조회가 지연되고 있습니다. 잠시 후 다시 시도해주세요."),
    DATABASE_ERROR("DATABASE_ERROR", "데이터 처리 중 오류가 발생했습니다. 잠시 후 다시 시도해주세요."),
    EXTERNAL_API_UNAVAILABLE("EXTERNAL_API_UNAVAILABLE", "외부 서비스에 연결할 수 없습니다. 잠시 후 다시 시도해주세요."),
    EXTERNAL_API_ERROR("EXTERNAL_API_ERROR", "외부 서비스 연동 중 오류가 발생했습니다. 잠시 후 다시 시도해주세요."),
    EMAIL_ALREADY_REGISTERED("EMAIL_ALREADY_REGISTERED", "이미 가입된 이메일입니다."),
    VERIFICATION_NOT_FOUND("VERIFICATION_NOT_FOUND", "인증 요청 내역을 찾을 수 없습니다."),
    VERIFICATION_EXPIRED("VERIFICATION_EXPIRED", "인증코드가 만료되었습니다."),
    VERIFICATION_CODE_MISMATCH("VERIFICATION_CODE_MISMATCH", "인증코드가 일치하지 않습니다."),
    INVALID_CREDENTIALS("INVALID_CREDENTIALS", "이메일 또는 비밀번호가 일치하지 않습니다."),
    EMAIL_REQUIRED("EMAIL_REQUIRED", "이메일을 입력해주세요."),
    INVALID_EMAIL_FORMAT("INVALID_EMAIL_FORMAT", "올바른 이메일 형식이 아닙니다."),
    EMAIL_TOO_LONG("EMAIL_TOO_LONG", "이메일은 50자 이하로 입력해주세요."),
    PASSWORD_REQUIRED("PASSWORD_REQUIRED", "비밀번호를 입력해주세요."),
    INVALID_PASSWORD_LENGTH("INVALID_PASSWORD_LENGTH", "비밀번호는 8~20자로 입력해주세요."),
    VERIFICATION_CODE_REQUIRED("VERIFICATION_CODE_REQUIRED", "인증코드를 입력해주세요."),
    INVALID_VERIFICATION_CODE_LENGTH("INVALID_VERIFICATION_CODE_LENGTH", "인증코드 자릿수가 올바르지 않습니다."),
    UNAUTHORIZED("UNAUTHORIZED", "로그인이 필요합니다."),
    RECOVERY_EMAIL_REQUIRED("RECOVERY_EMAIL_REQUIRED", "복구 이메일을 입력해주세요."),
    INVALID_RECOVERY_EMAIL_FORMAT("INVALID_RECOVERY_EMAIL_FORMAT", "올바른 복구 이메일 형식이 아닙니다."),
    RECOVERY_EMAIL_TOO_LONG("RECOVERY_EMAIL_TOO_LONG", "복구 이메일은 50자 이하로 입력해주세요."),
    RECOVERY_EMAIL_SAME_AS_EMAIL("RECOVERY_EMAIL_SAME_AS_EMAIL", "복구 이메일은 로그인 이메일과 달라야 합니다."),
    RECOVERY_EMAIL_ALREADY_REGISTERED("RECOVERY_EMAIL_ALREADY_REGISTERED", "이미 사용 중인 복구 이메일입니다."),
    RECOVERY_EMAIL_NOT_FOUND("RECOVERY_EMAIL_NOT_FOUND", "등록되지 않은 복구 이메일입니다."),
    EMAIL_NOT_FOUND("EMAIL_NOT_FOUND", "등록되지 않은 이메일입니다."),
    EMAIL_NOT_VERIFIED("EMAIL_NOT_VERIFIED", "이메일 인증을 완료해주세요."),
    RESET_PASSWORD_NOT_VERIFIED("RESET_PASSWORD_NOT_VERIFIED", "비밀번호 재설정 인증을 완료해주세요."),
    CURRENT_PASSWORD_MISMATCH("CURRENT_PASSWORD_MISMATCH", "현재 비밀번호가 일치하지 않습니다."),
    VERIFICATION_REQUEST_LIMIT_EXCEEDED("VERIFICATION_REQUEST_LIMIT_EXCEEDED", "인증코드 요청 횟수를 초과했습니다. 10분 뒤 다시 시도해주세요."),
    VERIFICATION_ATTEMPTS_EXCEEDED("VERIFICATION_ATTEMPTS_EXCEEDED", "인증코드 시도 횟수를 초과했습니다. 인증코드를 다시 요청해주세요."),
    STOCK_NOT_FOUND("STOCK_NOT_FOUND", "존재하지 않는 종목입니다."),
    STOCK_DETAIL_NOT_FOUND("STOCK_DETAIL_NOT_FOUND", "종목 상세정보를 찾을 수 없습니다."),
    USER_STOCK_NOT_FOUND("USER_STOCK_NOT_FOUND", "등록되지 않은 관심종목입니다."),
    STOCK_CHAT_QUESTION_REQUIRED("STOCK_CHAT_QUESTION_REQUIRED", "질문을 입력해주세요."),
    STOCK_CHAT_QUESTION_TOO_LONG("STOCK_CHAT_QUESTION_TOO_LONG", "질문은 300자 이하로 입력해주세요."),
    STOCK_CHAT_FAILED("STOCK_CHAT_FAILED", "AI 응답을 받아오지 못했습니다. 잠시 후 다시 시도해주세요."),
    INVALID_MAIL_DISPATCH_TIME("INVALID_MAIL_DISPATCH_TIME", "발송시간대는 30분 단위(예: 09:00, 09:30)로만 설정할 수 있습니다."),
}
